CREATE TABLE IF NOT EXISTS SZA010 (
    SZACOD INT PRIMARY KEY AUTO_INCREMENT,
    SZACIDADE CHAR(50) NOT NULL,
    SZAUF CHAR(2) NOT NULL,
    SZAIGBE CHAR(7) NOT NULL
);

CREATE TABLE IF NOT EXISTS QI2010 (
    QI2COD INT PRIMARY KEY AUTO_INCREMENT,
    QI2NOME CHAR(50) NOT NULL,
    QI2CPF CHAR(11) NOT NULL,
    QI2DTNASC DATE NOT NULL,
    QI2EMAIL CHAR(50) NOT NULL,
    QI2SEXO CHAR(1) NOT NULL,
    QI2SENHA CHAR(32) NOT NULL,
    QI2TIPO CHAR(1) NOT NULL DEFAULT 'C',
    QI2ATIVO CHAR(1) NOT NULL DEFAULT 'S',
    SZACOD INT,
    FOREIGN KEY (SZACOD) REFERENCES SZA010(SZACOD) ON DELETE CASCADE
);